[package]
name = "scafalra"
version = "0.6.0"
edition = "2021"
publish = false
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "scafalra is a command-line interface tool for manage scaffold"
repository = "https://github.com/shixinhuang99/scafalra"
homepage = "https://github.com/shixinhuang99/scafalra"
documentation = "https://github.com/shixinhuang99/scafalra"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["scaffold"]

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
once_cell = "1.17.1"
regex = "1.7.3"
remove_dir_all = "0.8.2"
serde = { version = "1.0.158", features = ["derive"] }
tabled = { version = "0.11.1", features = ["color"] }
term_grid = "0.2.0"
toml = "0.7.3"
ureq = { version = "2.6.2", features = ["json"] }
tar = "0.4.38"
flate2 = "1.0.25"

[dev-dependencies]
mockito = "1.0.2"
pretty_assertions = "1.3.0"
tempfile = "3.5.0"
