[package]
name = "scafalra"
version = "0.6.0"
edition = "2021"
publish = false
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
description = "scafalra is a command-line interface tool for manage scaffold"
repository = "https://github.com/shixinhuang99/scafalra"
homepage = "https://github.com/shixinhuang99/scafalra"
documentation = "https://github.com/shixinhuang99/scafalra"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["scaffold"]

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.13", features = ["derive"] }
once_cell = "1.17.1"
regex = "1.7.3"
remove_dir_all = "0.8.2"
serde = { version = "1.0.158", features = ["derive"] }
toml = "0.7.3"
ureq = { version = "2.6.2", features = ["json"] }
zip = "0.6.4"

[dev-dependencies]
pretty_assertions = "1.3.0"
tempfile = "3.5.0"
