[target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "target-feature=+crt-static"]
# linker = "x86_64-linux-gnu-gcc"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
