name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  general-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --all-targets

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Fmt
        run: cargo fmt --all -- --check

  tests:
    needs: general-check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          [
            aarch64-apple-darwin,
            x86_64-apple-darwin,
            aarch64-unknown-linux-musl,
            x86_64-unknown-linux-musl,
            arm-unknown-linux-musleabihf,
            armv7-unknown-linux-musleabihf,
            x86_64-pc-windows-msvc,
          ]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Podman
        run: |
          sudo apt-get -y update
          sudo apt-get -y install podman
          podman ps -a

      - name: Install Cross
        run: cargo install cross

      - name: Cross tests
        run: cross test --target ${{ matrix.target }}
